version: "3"
services:
  
  python:
    build: ./python
    container_name: fate_python
    ports:
      - "9380:9380"
      - "9360:9360"
    volumes:
      - "../fate/log:/fate/logs"
      - "../fate/data:/fate/fate_flow"
    command: bash docker-entrypoint.sh
  
  fateboard:
    build: ./fateboard
    container_name: fate_fateboard
    links:
      - python
    ports:
      - "8080:8080"
    depends_on:
      - python
    volumes:
      - "../fate/log:/data/projects/fate/python/logs"
      - "../fate/data:/fate/fate_flow"
    command: bash docker-entrypoint.sh
